// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOzgFYjNzqDBVzDRQ7aFl0fIKpHYdGuNQ',
    appId: '1:230136178640:web:5e05c5c6b30bb7721bfbd5',
    messagingSenderId: '230136178640',
    projectId: 'ceylon-share-tour',
    authDomain: 'ceylon-share-tour.firebaseapp.com',
    storageBucket: 'ceylon-share-tour.firebasestorage.app',
    measurementId: 'G-KN1MFSM2BN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCU76ZdlAQiag6lPNOt2hRoVPjEacAkfuk',
    appId: '1:230136178640:android:9fa53c7fd20d8a061bfbd5',
    messagingSenderId: '230136178640',
    projectId: 'ceylon-share-tour',
    storageBucket: 'ceylon-share-tour.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrY-PJ2pnuqe-qzP4cz5ssVsqMQgIgxJ4',
    appId: '1:230136178640:ios:4b3677c86edc60711bfbd5',
    messagingSenderId: '230136178640',
    projectId: 'ceylon-share-tour',
    storageBucket: 'ceylon-share-tour.firebasestorage.app',
    iosBundleId: 'com.example.tripShareApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrY-PJ2pnuqe-qzP4cz5ssVsqMQgIgxJ4',
    appId: '1:230136178640:ios:4b3677c86edc60711bfbd5',
    messagingSenderId: '230136178640',
    projectId: 'ceylon-share-tour',
    storageBucket: 'ceylon-share-tour.firebasestorage.app',
    iosBundleId: 'com.example.tripShareApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOzgFYjNzqDBVzDRQ7aFl0fIKpHYdGuNQ',
    appId: '1:230136178640:web:ab322ecf577602f81bfbd5',
    messagingSenderId: '230136178640',
    projectId: 'ceylon-share-tour',
    authDomain: 'ceylon-share-tour.firebaseapp.com',
    storageBucket: 'ceylon-share-tour.firebasestorage.app',
    measurementId: 'G-DGLKCC9Y29',
  );
}
