export interface Tour {
  id: string;
  title: string;
  category: string;
  description: string;
  price: number;
  images: string[];
  seat_count: number;
  start_location: string;
  start_day: string;
  start_time: string;
  start_time_period: 'AM' | 'PM';
  end_location: string;
  end_day: string;
  end_time: string;
  end_time_period: 'AM' | 'PM';
  booking_close_time: string;
  booking_close_period: 'AM' | 'PM';
  booking_close_date: string;
  route: string[];
  operator_name: string;
  whats_included: string;
  tour_features: string;
  location?: string;
  duration?: string;
  start_time_location?: string;
  last_joining_time?: string;
  end_time_location?: string;
  created_at?: unknown;
}
